import React from 'react';

export default function Footer() {
  return (
    <footer id="contact" className="bg-black text-slate-400 pt-16 pb-8 px-6 md:px-16 border-t border-neutral-900">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-10 mb-12">
        
        {/* Footer Left Column - Social Media */}
        <div className="space-y-4">
          <h4 className="text-white font-bold text-sm tracking-widest uppercase">Image Generated by</h4>
          <div className="flex space-x-4 pt-2">
            
            {/* Facebook SVG */}
            <a href="#" className="hover:text-[#EAB308] transition-colors p-2 bg-neutral-900 rounded-full" aria-label="Facebook">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
              </svg>
            </a>

            {/* Twitter / X SVG */}
            <a href="#" className="hover:text-[#EAB308] transition-colors p-2 bg-neutral-900 rounded-full" aria-label="Twitter">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"></path>
              </svg>
            </a>

            {/* Instagram SVG */}
            <a href="#" className="hover:text-[#EAB308] transition-colors p-2 bg-neutral-900 rounded-full" aria-label="Instagram">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
              </svg>
            </a>

          </div>
        </div>

        {/* Footer Middle Column */}
        <div className="space-y-3">
          <h4 className="text-white font-bold text-sm tracking-widest uppercase mb-1">About Us</h4>
          <ul className="space-y-2 text-sm">
            <li><a href="#services" className="hover:text-[#EAB308] transition-colors">Our Services</a></li>
            <li><a href="#about" className="hover:text-[#EAB308] transition-colors">About Us</a></li>
            <li><a href="#contact" className="hover:text-[#EAB308] transition-colors">Contact</a></li>
          </ul>
        </div>

        {/* Footer Right Column */}
        <div className="space-y-3">
          <h4 className="text-white font-bold text-sm tracking-widest uppercase mb-1">Footer</h4>
          <ul className="space-y-2 text-sm">
            <li><a href="#" className="hover:text-[#EAB308] transition-colors">Privacy Policy</a></li>
            <li><a href="#" className="hover:text-[#EAB308] transition-colors">Standard Info</a></li>
            <li><a href="#" className="hover:text-[#EAB308] transition-colors">Contact Us</a></li>
          </ul>
        </div>
      </div>

      {/* Bottom Bar */}
      <div className="max-w-7xl mx-auto pt-8 border-t border-neutral-900 flex flex-col sm:flex-row justify-between items-center text-xs text-neutral-600 gap-4">
        <p>Image Generated by Gemini</p>
        <p>&copy; {new Date().getFullYear()} Hello 11 Home. All rights reserved.</p>
      </div>
    </footer>
  );
}